"""FastAPI backend for the recruitment chatbot — the API half of chatbot/.

Separate module from the CLI (workers/chat.py) but reuses its retrieval and
prompt pieces, so CLI and web answers stay identical. The static frontend
(chatbot/frontend) is served by this process locally and can be hosted
elsewhere later by pointing its config.js at this API. This half stays
in-network: it needs the DB and (directly or via the embedding service)
the BGE-M3 model.

Scale features (all env-tunable, safe defaults for laptop dev):
  CHATBOT_API_TOKEN      shared bearer token; unset = auth off (local dev)
  CHATBOT_ALLOWED_ORIGINS comma-separated CORS origins (default localhost:8000)
  CHATBOT_RATE_LIMIT     chat requests/min per client IP (default 20, 0 = off)
  CHATBOT_DB_POOL_SIZE   Postgres connection pool size (default 5)
  CHATBOT_WORKERS        uvicorn worker processes (default 1) — with >1 set
                         EMBED_SERVICE_URL or every worker loads the 2 GB model
  EMBED_SERVICE_URL      embedding microservice (embed_service.py); unset =
                         load BGE-M3 in-process
  CHATBOT_HOST           bind address (default 127.0.0.1; 0.0.0.0 in Docker)

Endpoints: GET /api/health, POST /api/chat (JSON), POST /api/chat/stream (SSE:
meta -> token* -> done, or error).

Run:  py chatbot/api/server.py
"""

from __future__ import annotations

import hmac
import json
import logging
import os
import re
import sys
import threading
import time
import uuid
from collections import defaultdict, deque
from contextlib import asynccontextmanager
from pathlib import Path

import uvicorn
from dotenv import load_dotenv
from fastapi import Depends, FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from fastapi.staticfiles import StaticFiles
from psycopg_pool import ConnectionPool
from pydantic import BaseModel, Field

ROOT = Path(__file__).resolve().parents[2]
load_dotenv(ROOT / ".env")
sys.path.insert(0, str(ROOT / "workers"))
from chat import (  # noqa: E402
    CHUNKS_SQL, SYSTEM_PROMPT, TOP_JOBS, boolean_prompt, build_boolean_strings,
    build_keyword_bank, build_user_message, condense_question, extract_job_ids,
    make_client, merge_job_ids, normalize_job_title, overview_block,
    parse_boolean_terms,
)
import starters  # noqa: E402
from embed_worker import get_conn_string, load_model  # noqa: E402
from hybrid_search import embed_query, run_search  # noqa: E402

FRONTEND_DIR = ROOT / "chatbot" / "frontend"
MAX_HISTORY_TURNS = 20  # bare Q/A pairs kept per request — bounds prompt size
OVERVIEW_TTL = 60  # seconds; scraper only runs every 5 min, so this is fresh

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
log = logging.getLogger("chatbot")

state: dict = {}
model_lock = threading.Lock()  # in-process BGE-M3 encode isn't thread-safe
overview_cache = {"text": "", "at": 0.0}
overview_lock = threading.Lock()
rate_buckets: dict[str, deque] = defaultdict(deque)
rate_lock = threading.Lock()


@asynccontextmanager
async def lifespan(app: FastAPI):
    state["pool"] = ConnectionPool(
        get_conn_string(),
        min_size=1,
        max_size=int(os.environ.get("CHATBOT_DB_POOL_SIZE", "5")),
        open=True,
    )
    state["client"] = make_client()  # fails fast on a missing LLM_API_KEY
    embed_url = os.environ.get("EMBED_SERVICE_URL")
    # load_model() returns a RemoteEmbedder when EMBED_SERVICE_URL is set
    # (local embed_service.py or the Modal deployment), else in-process BGE-M3.
    state["model"] = load_model()
    state["in_process_model"] = not embed_url
    if embed_url:
        log.info("using embedding service at %s", embed_url)
    log.info("chatbot ready: http://localhost:8000")
    yield
    state["pool"].close()


app = FastAPI(title="Recruitment chatbot API", lifespan=lifespan)
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        o.strip()
        for o in os.environ.get(
            "CHATBOT_ALLOWED_ORIGINS", "http://localhost:8000"
        ).split(",")
        if o.strip()
    ],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def revalidate_static(request: Request, call_next):
    """no-cache on the frontend files so browsers revalidate on every load —
    unchanged files still 304, but UI fixes show up without a hard refresh."""
    response = await call_next(request)
    if not request.url.path.startswith("/api/"):
        response.headers["Cache-Control"] = "no-cache"
    return response


def valid_email_token(value: str) -> str | None:
    """Verify a per-person 'email:signature' token (generated by
    scripts/make_token.py: HMAC-SHA256 of the email under
    TOKEN_SIGNING_SECRET). Returns the email when the signature matches and
    the domain is allowed — no token database needed."""
    secret = os.environ.get("TOKEN_SIGNING_SECRET")
    if not secret or ":" not in value:
        return None
    email, _, sig = value.rpartition(":")
    email = email.strip().lower()
    domain = os.environ.get("ALLOWED_EMAIL_DOMAIN", "vdartinc.com")
    local = email[: -len(f"@{domain}")] if email.endswith(f"@{domain}") else ""
    if not local or "@" in local:  # must be <someone>@<domain>, nothing else
        return None
    expected = hmac.new(secret.encode(), email.encode(), "sha256").hexdigest()[:40]
    return email if hmac.compare_digest(sig, expected) else None


def require_token(request: Request) -> None:
    """Bearer auth, two accepted token forms: a per-person email token
    ('email:signature', see valid_email_token) or the legacy shared
    CHATBOT_API_TOKEN. With neither env set, auth is off (local dev).
    A verified email lands on request.state.user_email for attribution."""
    shared = os.environ.get("CHATBOT_API_TOKEN")
    signing = os.environ.get("TOKEN_SIGNING_SECRET")
    request.state.user_email = None
    if not shared and not signing:
        return
    auth = request.headers.get("authorization", "")
    value = auth[7:] if auth.startswith("Bearer ") else ""
    email = valid_email_token(value)
    if email:
        request.state.user_email = email
        return
    if shared and value and hmac.compare_digest(value, shared):
        return
    raise HTTPException(status_code=401, detail="Missing or invalid API token")


def rate_limit(request: Request) -> None:
    """Sliding-window per-IP limit on chat endpoints. In-memory, so it is
    per-worker — good enough until there's a shared store to justify Redis."""
    limit = int(os.environ.get("CHATBOT_RATE_LIMIT", "20"))
    if limit <= 0:
        return
    ip = request.client.host if request.client else "unknown"
    now = time.monotonic()
    with rate_lock:
        bucket = rate_buckets[ip]
        while bucket and now - bucket[0] > 60:
            bucket.popleft()
        if len(bucket) >= limit:
            raise HTTPException(
                status_code=429, detail="Rate limit exceeded — try again in a minute"
            )
        bucket.append(now)


# --- recruiter note masking — parity with utils/maskJobs.ts (emails/phones).
# Person names in free text are the same documented gap as the scrape side:
# regex can't catch arbitrary names, so the UI tells recruiters not to type
# names/contact details into notes.
EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")
PHONE_RE = re.compile(r"(?<!\d)(?:\(\d{3}\)\s?|\d{3}[-.\s])\d{3}[-.\s]\d{4}(?!\d)")


def mask_note(text: str) -> tuple[str, int]:
    """Redact emails and US phone numbers; returns (masked text, hit count)."""
    masked, n_email = EMAIL_RE.subn("[REDACTED_EMAIL]", text)
    masked, n_phone = PHONE_RE.subn("[REDACTED_PHONE]", masked)
    return masked, n_email + n_phone


class Turn(BaseModel):
    role: str = Field(pattern="^(user|assistant)$")
    content: str


class ChatRequest(BaseModel):
    question: str = Field(min_length=1, max_length=2000)
    history: list[Turn] = []


def cached_overview() -> str:
    with overview_lock:
        if time.monotonic() - overview_cache["at"] > OVERVIEW_TTL:
            with state["pool"].connection() as conn:
                overview_cache["text"] = overview_block(conn)
            overview_cache["at"] = time.monotonic()
        return overview_cache["text"]


def retrieve(question: str, focus_ids: list[str]) -> tuple[str, list[dict]]:
    """Rank jobs for the question; return (chunk context block, job metadata).
    focus_ids (postings already discussed or explicitly named) are pinned
    ahead of fresh retrieval hits. Encode happens BEFORE a pool connection is
    taken, so slow CPU embedding never starves the pool."""
    if state["in_process_model"]:
        with model_lock:
            literal = embed_query(state["model"], question)
    else:
        literal = embed_query(state["model"], question)

    with state["pool"].connection() as conn:
        hits = run_search(conn, literal, question, limit=TOP_JOBS)
        job_ids = merge_job_ids(focus_ids, [job_id for job_id, *_ in hits])
        if not job_ids:
            return "", []
        rows = conn.execute(CHUNKS_SQL, (job_ids, job_ids)).fetchall()

    blocks: list[str] = []
    jobs: list[dict] = []
    current = None
    for job_id, title, source, content in rows:
        if job_id != current:
            blocks.append(f"### {job_id} — {title}")
            jobs.append({"job_id": job_id, "title": title})
            current = job_id
        blocks.append(f"[{source}]\n{content}")
    return "\n\n".join(blocks), jobs


def prepare(req: ChatRequest, rid: str) -> tuple[list[dict], str, list[dict], dict]:
    """Shared pre-LLM pipeline: condense -> retrieve -> build messages.
    Returns (messages, answer-model name, jobs, stage timings in ms)."""
    timings: dict = {}
    history = [t.model_dump() for t in req.history[-MAX_HISTORY_TURNS:]]

    t0 = time.perf_counter()
    try:
        search_query = condense_question(state["client"], history, req.question)
    except Exception as exc:
        log.warning("[%s] condense failed, using raw question: %s", rid, exc)
        search_query = req.question  # degraded retrieval beats a failed request
    timings["condense_ms"] = round((time.perf_counter() - t0) * 1000)

    # Pin postings the conversation is already about: ids named in the
    # question first, then the most recently cited ones (max 3, so fresh
    # retrieval keeps at least half the context slots).
    newest_first = [t["content"] for t in reversed(history)]
    focus_ids = extract_job_ids(req.question, *newest_first)[:3]

    t0 = time.perf_counter()
    context, jobs = retrieve(search_query, focus_ids)
    timings["retrieve_ms"] = round((time.perf_counter() - t0) * 1000)

    user_msg = build_user_message(cached_overview(), context, req.question)
    messages = [{"role": "system", "content": SYSTEM_PROMPT}, *history,
                {"role": "user", "content": user_msg}]
    model_name = os.environ.get("LLM_MODEL", "llama-3.3-70b-versatile")
    return messages, model_name, jobs, timings


class NoteRequest(BaseModel):
    job_id: str = Field(pattern=r"^[A-Z]+\d+$", max_length=40)
    note: str = Field(min_length=3, max_length=4000)


@app.post("/api/notes", dependencies=[Depends(require_token), Depends(rate_limit)])
def add_note(req: NoteRequest, request: Request) -> dict:
    """Attach a recruiter intake note (phone-call info) to a job. The note is
    masked, stored in job_notes, and mirrored into job_chunks with a
    synchronously computed embedding so it is immediately searchable.
    With email-token auth the verified email is stored as the author."""
    masked, redactions = mask_note(req.note.strip())
    author = getattr(request.state, "user_email", None)

    with state["pool"].connection() as conn:
        row = conn.execute(
            "select title from jobs where job_id = %s", (req.job_id,)
        ).fetchone()
        if row is None:
            raise HTTPException(status_code=404, detail=f"Unknown job ID {req.job_id}")
        title = row[0]
        note_row = conn.execute(
            "insert into job_notes (job_id, note, author) values (%s, %s, %s)"
            " returning id, created_at",
            (req.job_id, masked, author),
        ).fetchone()
        note_id, created_at = note_row

    content = f"Recruiter note ({created_at:%Y-%m-%d}): {masked}"
    # Embed now (1-3s) instead of waiting for the embed worker's next pass —
    # a recruiter who just saved a note expects it findable immediately.
    if state["in_process_model"]:
        with model_lock:
            literal = embed_query(state["model"], content)
    else:
        literal = embed_query(state["model"], content)

    with state["pool"].connection() as conn:
        conn.execute(
            "insert into job_chunks (job_id, chunk_index, source, content, embedding)"
            " values (%s, %s, 'recruiter-note', %s, %s::vector)",
            (req.job_id, 100_000 + note_id, content, literal),
        )

    log.info("note %d added to %s (%d redaction(s))", note_id, req.job_id, redactions)
    return {"job_id": req.job_id, "title": title, "note_id": note_id,
            "redactions": redactions}


@app.get("/api/notes/{job_id}", dependencies=[Depends(require_token)])
def list_notes(job_id: str) -> dict:
    with state["pool"].connection() as conn:
        row = conn.execute(
            "select title from jobs where job_id = %s", (job_id,)
        ).fetchone()
        if row is None:
            raise HTTPException(status_code=404, detail=f"Unknown job ID {job_id}")
        notes = conn.execute(
            "select id, note, created_at, author from job_notes where job_id = %s"
            " order by created_at",
            (job_id,),
        ).fetchall()
    return {"job_id": job_id, "title": row[0],
            "notes": [{"id": n_id, "note": text, "created_at": f"{ts:%Y-%m-%d %H:%M}",
                       "author": author}
                      for n_id, text, ts, author in notes]}


@app.delete("/api/notes/{note_id}",
            dependencies=[Depends(require_token), Depends(rate_limit)])
def delete_note(note_id: int, request: Request) -> dict:
    """Remove a note and its searchable mirror chunk. Any authenticated user
    can delete any note (recruiters cover each other's reqs); with email-token
    auth the deletion is at least attributed in the server log."""
    with state["pool"].connection() as conn:
        row = conn.execute(
            "delete from job_notes where id = %s returning job_id", (note_id,)
        ).fetchone()
        if row is None:
            raise HTTPException(status_code=404, detail=f"No note #{note_id}")
        conn.execute(
            "delete from job_chunks where job_id = %s and chunk_index = %s",
            (row[0], 100_000 + note_id),
        )
    log.info("note %d deleted from %s by %s", note_id, row[0],
             getattr(request.state, "user_email", None) or "shared-token user")
    return {"deleted": note_id, "job_id": row[0]}


class BooleanRequest(BaseModel):
    job_id: str = Field(pattern=r"^[A-Z]+\d+$", max_length=40)
    # Phase 1: recruiter's correction of the inferred occupation, if any.
    role_override: str | None = Field(default=None, max_length=200)


@app.post("/api/boolean", dependencies=[Depends(require_token), Depends(rate_limit)])
def boolean_search(req: BooleanRequest) -> dict:
    """Generate tiered candidate-sourcing Boolean strings for one job (Module 2
    preview): precision / balanced / discovery, plus a keyword bank. The LLM
    only EXTRACTS and TIERS candidate-facing terms from the masked posting;
    build_boolean_strings assembles the strings deterministically, so
    operators/quoting/parentheses are valid regardless of the model. Education
    and experience stay in the bank as screening criteria, never in a string."""
    rid = uuid.uuid4().hex[:8]
    with state["pool"].connection() as conn:
        row = conn.execute(
            "select title from jobs where job_id = %s", (req.job_id,)
        ).fetchone()
        if row is None:
            raise HTTPException(status_code=404, detail=f"Unknown job ID {req.job_id}")
        title = row[0]
        rows = conn.execute(CHUNKS_SQL, ([req.job_id], [req.job_id])).fetchall()

    # Phase 0: separate the raw VMS title from a clean market title. Internal
    # level/grade/experience/employment markers become metadata (for display/
    # audit), never keywords. The model gets the normalized title to anchor on.
    normalized_title, title_meta = normalize_job_title(title)

    # All chunk text is already PII-masked (same as chat retrieval), incl.
    # recruiter notes — those often carry the real must-have skills.
    context = "\n\n".join(f"[{source}]\n{content}" for _, _, source, content in rows)
    context = (context.strip() or title)[:6000]  # title fallback if unchunked

    messages = [{"role": "user",
                 "content": boolean_prompt(normalized_title or title, context,
                                           role_override=req.role_override)}]
    model_name = os.environ.get("LLM_MODEL", "llama-3.3-70b-versatile")
    try:
        # Bank rows are derived in Python now, so the model emits less — 600
        # tokens covers three tiers + education + exclusions comfortably.
        resp = state["client"].chat.completions.create(
            model=model_name, messages=messages, max_tokens=600
        )
    except Exception as exc:
        log.error("[%s] boolean LLM request failed: %s", rid, exc)
        status, payload = llm_error_payload(exc)
        raise HTTPException(status_code=status, detail=payload)

    parsed = parse_boolean_terms(resp.choices[0].message.content or "")
    tiers = build_boolean_strings(parsed)
    if not any(t["string"] for t in tiers):
        raise HTTPException(
            status_code=502,
            detail={"code": "boolean_empty",
                    "message": "Could not derive search terms for this posting. "
                               "Try again, or add detail with /note first."},
        )
    log.info("[%s] boolean for %s: tiers=%s", rid, req.job_id,
             [len(t["string"]) for t in tiers])
    return {"job_id": req.job_id, "title": title,  # title = raw (back-compat)
            "raw_job_title": title, "normalized_search_title": normalized_title,
            "title_metadata": title_meta, "role": parsed["role"], "tiers": tiers,
            "bank": build_keyword_bank(parsed)}


@app.get("/api/starters", dependencies=[Depends(rate_limit)])
def starters_chips() -> dict:
    """Up to four action-oriented homepage chips chosen from live VMS state,
    each with an exact count (VMS Assistant Starter Questions spec). Counts only
    (no job details), so this is auth-free — the homepage shows live counts
    immediately; job-level detail is gated behind /api/starters/answer."""
    with state["pool"].connection() as conn:
        chips = starters.select_chips(conn)
    return {"chips": chips}


class StarterAnswerRequest(BaseModel):
    key: str = Field(pattern=r"^[a-z_]+$", max_length=40)


@app.post("/api/starters/answer",
          dependencies=[Depends(require_token), Depends(rate_limit)])
def starters_answer(req: StarterAnswerRequest) -> dict:
    """Structured, SQL-backed answer for one chip — cited Job IDs + the reason
    each appears (spec AC-06/08). No LLM, so counts/rows can't be hallucinated."""
    with state["pool"].connection() as conn:
        result = starters.answer(conn, req.key)
    if result is None:
        raise HTTPException(status_code=404, detail=f"Unknown starter '{req.key}'")
    return result


class FeedbackRequest(BaseModel):
    job_id: str = Field(pattern=r"^[A-Z]+\d+$", max_length=40)
    action: str = Field(max_length=40)
    platform: str | None = Field(default=None, max_length=20)
    query: str | None = Field(default=None, max_length=2000)


@app.post("/api/boolean/feedback",
          dependencies=[Depends(require_token), Depends(rate_limit)])
def boolean_feedback(req: FeedbackRequest, request: Request) -> dict:
    """Capture recruiter search actions/edits for future tuning (spec §13 /
    AC-16 feedback). The query is masked, job-derived Boolean text — no
    candidate-sensitive data. No DB yet: a structured server-log line only; a
    job_search_log table is the follow-on when we want aggregates."""
    who = getattr(request.state, "user_email", None) or "shared-token user"
    log.info("boolean-feedback job=%s action=%s platform=%s qlen=%d by=%s",
             req.job_id, req.action, req.platform or "-", len(req.query or ""), who)
    return {"ok": True}


@app.post("/api/warmup", dependencies=[Depends(require_token)])
def warmup() -> dict:
    """Fire a 1-token LLM call to trigger the Qwen GPU cold start ahead of real
    use. The frontend calls this on page load (best-effort) so the model is
    booting while the recruiter reads/types, hiding most of the ~1-3 min cold
    start. Cheap: one token, and it no-ops fast once the container is warm."""
    model_name = os.environ.get("LLM_MODEL", "llama-3.3-70b-versatile")
    try:
        state["client"].chat.completions.create(
            model=model_name, messages=[{"role": "user", "content": "ping"}],
            max_tokens=1,
        )
        return {"warm": True}
    except Exception as exc:  # never surface details — this is best-effort
        log.info("warmup call failed (model likely still booting): %s", exc)
        return {"warm": False}


@app.get("/api/health")
def health() -> dict:
    return {
        "status": "ok",
        "model": os.environ.get("LLM_MODEL", "llama-3.3-70b-versatile"),
        "embedding": "service" if not state.get("in_process_model", True) else "in-process",
        "auth": bool(os.environ.get("CHATBOT_API_TOKEN")),
    }


@app.post("/api/chat", dependencies=[Depends(require_token), Depends(rate_limit)])
def chat(req: ChatRequest) -> dict:
    rid = uuid.uuid4().hex[:8]
    t_start = time.perf_counter()
    messages, model_name, jobs, timings = prepare(req, rid)
    t0 = time.perf_counter()
    try:
        resp = state["client"].chat.completions.create(model=model_name, messages=messages)
    except Exception as exc:
        log.error("[%s] LLM request failed: %s", rid, exc)
        status, payload = llm_error_payload(exc)
        raise HTTPException(status_code=status, detail=payload)
    timings["llm_ms"] = round((time.perf_counter() - t0) * 1000)
    timings["total_ms"] = round((time.perf_counter() - t_start) * 1000)
    log.info("[%s] chat qlen=%d %s", rid, len(req.question), timings)
    answer = resp.choices[0].message.content
    # Chip only the postings the answer actually cites — the full retrieval
    # context (up to 6 jobs) confuses users when most weren't relevant.
    cited = set(extract_job_ids(answer or ""))
    return {"answer": answer, "jobs": [j for j in jobs if j["job_id"] in cited]}


# Providers phrase retry hints like "try again in 51m40.895s" / "in 7.66s".
RETRY_HINT_RE = re.compile(r"try again in (?:(\d+)h)?(?:(\d+)m)?([\d.]+)s", re.IGNORECASE)


def llm_error_payload(exc: Exception) -> tuple[int, dict]:
    """Map an LLM-call failure to (http_status, {code, message}) that is safe
    to show users. The raw exception (org ids, quota numbers) is logged by the
    caller — never sent to the browser."""
    raw = str(exc)
    status = getattr(exc, "status_code", None)
    if status == 429:
        message = "The AI service has reached its usage limit."
        hint = RETRY_HINT_RE.search(raw)
        if hint:
            hours, mins, secs = (int(hint.group(1) or 0), int(hint.group(2) or 0),
                                 float(hint.group(3)))
            total_min = hours * 60 + mins + (1 if secs > 0 else 0)
            message += (f" Try again in about {total_min} minute(s)."
                        if total_min > 1 else " Try again in a minute.")
        else:
            message += " Please try again in a few minutes."
        return 429, {"code": "llm_rate_limited", "message": message}
    if status in (401, 403):
        return 502, {"code": "llm_auth_failed",
                     "message": "The AI service rejected the server's credentials — "
                                "the LLM API key needs attention."}
    if status is None:  # connection/timeout errors have no HTTP status
        return 502, {"code": "llm_unreachable",
                     "message": "Could not reach the AI service. Please try again; "
                                "if it persists, contact the admin."}
    return 502, {"code": "llm_error",
                 "message": "The AI service failed to answer. Please try again."}


def sse(event: str, data: dict) -> str:
    return f"event: {event}\ndata: {json.dumps(data)}\n\n"


@app.post("/api/chat/stream",
          dependencies=[Depends(require_token), Depends(rate_limit)])
def chat_stream(req: ChatRequest) -> StreamingResponse:
    rid = uuid.uuid4().hex[:8]

    def event_stream():
        t_start = time.perf_counter()
        try:
            messages, model_name, jobs, timings = prepare(req, rid)
            yield sse("meta", {"jobs": jobs})
            t0 = time.perf_counter()
            stream = state["client"].chat.completions.create(
                model=model_name, messages=messages, stream=True
            )
            for chunk in stream:
                delta = chunk.choices[0].delta.content if chunk.choices else None
                if delta:
                    yield sse("token", {"t": delta})
            timings["llm_ms"] = round((time.perf_counter() - t0) * 1000)
            timings["total_ms"] = round((time.perf_counter() - t_start) * 1000)
            log.info("[%s] stream qlen=%d %s", rid, len(req.question), timings)
            yield sse("done", {})
        except Exception as exc:  # stream already started — report in-band
            log.error("[%s] stream failed: %s", rid, exc)
            _, payload = llm_error_payload(exc)
            yield sse("error", payload)

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


# Mounted last so /api/* wins; html=True serves index.html at /.
app.mount("/", StaticFiles(directory=FRONTEND_DIR, html=True), name="frontend")


if __name__ == "__main__":
    workers = int(os.environ.get("CHATBOT_WORKERS", "1"))
    if workers > 1 and not os.environ.get("EMBED_SERVICE_URL"):
        print(
            "WARNING: CHATBOT_WORKERS>1 without EMBED_SERVICE_URL — every worker\n"
            "will load its own 2 GB BGE-M3 copy. Start chatbot/api/embed_service.py\n"
            "and set EMBED_SERVICE_URL=http://localhost:8100 instead.",
            flush=True,
        )
    uvicorn.run(
        "server:app",
        host=os.environ.get("CHATBOT_HOST", "127.0.0.1"),
        port=int(os.environ.get("CHATBOT_PORT", "8000")),
        workers=workers,
        app_dir=str(Path(__file__).parent),
    )
